version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    environment:
      MOCHA_FILE: ./test-results/mocha/report.xml
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install graphicsmagick
            yarn install
      - run:
          name: Run tests
          command: |
            yarn test-ci
      - store_test_results:
          path: test-results

  deploy-prod:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo yarn global add serverless
            yarn install
      - run:
          name: Deploy
          command: |
            sls deploy --stage production

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master